# Generated by Django 6.0.2 on 2026-04-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0002_event_event_capacity_event_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
