# Generated by Django 6.0.3 on 2026-05-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0002_project_creator_alter_projectcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrating',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diyprojects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectreview',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diyprojects.project'),
            preserve_default=False,
        ),
    ]
