# Generated by Django 6.0.3 on 2026-05-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0003_projectrating_project_projectreview_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
